/**
 * Content Plugin for Bun
 * 
 * Generates a virtual module that exports lazy loaders for all MDX content files.
 * Supports nested directories for variants:
 *   src/content/intro.mdx        → 'intro'
 *   src/content/intro/research.mdx → 'intro/research'
 * 
 * Usage:
 *   import { contentModules, contentIds } from 'virtual:content-modules';
 *   const loader = contentModules['intro'];
 *   const module = await loader();
 */

import type { BunPlugin } from 'bun';

const VIRTUAL_MODULE_ID = 'virtual:content-modules';

export const contentPlugin: BunPlugin = {
  name: 'content',
  
  setup(build) {
    // Resolve the virtual module
    build.onResolve({ filter: new RegExp(`^${VIRTUAL_MODULE_ID}$`) }, (args) => {
      return {
        path: args.path,
        namespace: 'content',
      };
    });
    
    // Generate the module content
    build.onLoad({ filter: /.*/, namespace: 'content' }, async () => {
      // Discover all MDX files in src/content/ (including nested)
      const glob = new Bun.Glob('**/*.mdx');
      const contentDir = 'src/content';
      const files: string[] = [];
      
      for await (const file of glob.scan({ cwd: contentDir })) {
        files.push(file);
      }
      
      // Generate import statements for each file
      // Extract node ID from path (e.g., 'intro.mdx' -> 'intro', 'intro/research.mdx' -> 'intro/research')
      const entries = files
        .map(file => {
          const nodeId = file.replace('.mdx', '');
          return `  '${nodeId}': () => import('@/content/${file}')`;
        })
        .join(',\n');
      
      const nodeIds = files.map(f => `'${f.replace('.mdx', '')}'`).join(', ');
      
      const code = `
/**
 * Auto-generated content module map
 * Generated by content-plugin at build time
 * 
 * Includes both base pages and variants (nested in subdirectories)
 */

export const contentModules: Record<string, () => Promise<{ default: any; meta: any }>> = {
${entries}
};

export const contentIds: string[] = [${nodeIds}];
`;
      
      return {
        contents: code,
        loader: 'ts',
      };
    });
  },
};

export default contentPlugin;
